FROM node:latest

RUN apt-get update && apt-get install -y redis-server

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the built application files (dist folder)
COPY dist ./dist

# Expose the necessary port (e.g., 3000)
EXPOSE 3000

# Command to start Redis and your Node.js application
CMD ["bash", "-c", "service redis-server start && node dist/api.js"]
