apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 #port from which the service accepts traffic
      targetPort: 6379 # port to which it routes
